version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: exshop
      POSTGRES_PASSWORD: exshop
      POSTGRES_DB: exshop
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
    ports:
      - 5432:5432